name: OmniConnect
version: '1.0.3'
main: org.respawn.omniConnect.Main
api-version: '1.16'
author: Daniyt_th
softdepend: [AAC, GrimAc, LightAntiCheat, Matrix, NCP, Spartan, Negativity, Vulcan, AzrovaEconomy, CoinManager, DZEoconomy, EsssentialsX, PlayerPoints, TokenManager, XConomy, AnarchyExploitFixes, ExploitFixer, LPX, KingdomsX, AuthMe, AuthMeReloaded, AutoRestart, CoreProtect, Maintenance, LibreLogin, LoginSystem, LuckPerms, NametagEdit, NLogin, PlugmanX, ServerRestorer, TAB, WorldEdit, WorldGuard, AdvancedBan, ChatControl, ChatControlRed, CleanStaffChat, CMI, EasyStaff, LibertyBans, StaffPlus]
commands:
  link:
    description: Minecraft ↔ Discord account link
    usage: /link

  discord:
    description: Discord Server link showcase
    usage: /discord

  store:
    description: Webshop link showcase
    usage: /store

  rules:
    description: Rules showcase
    usage: /rules

  website:
    description: Website link showcase
    usage: /website

  vote:
    description: Vote Site link showcase
    usage: /vote

  map:
    description: Map (Dynmap) link showcase
    usage: /map

  wiki:
    description: Wiki / Documention link showcase
    usage: /wiki


  omnireload:
    description: Reload OmniConnect
    usage: /omnireload
    permission: omniconnect.reload

  omnirestartbot:
    description: Restart the Discord bot
    usage: /omnirestartbot
    permission: omniconnect.restartbot

  discordstatus:
    description: Check Discord bot status
    usage: /discordstatus
    permission: omniconnect.status

  omniconnect:
    description: OmniConnect help menu
    usage: /omniconnect
    permission: omniconnect.help


permissions:
  omniconnect.reload:
    default: op
  omniconnect.restartbot:
    default: op
  omniconnect.status:
    default: op
