name: OmniConnect
version: '1.0.2'
main: org.respawn.omniConnect.Main
api-version: '1.16'
author: Daniyt_th
commands:
  link:
    description: Minecraft ↔ Discord account link
    usage: /link

  discord:
    description: Discord Server link showcase
    usage: /discord

  store:
    description: Webshop link showcase
    usage: /store

  rules:
    description: Rules showcase
    usage: /rules

  website:
    description: Website link showcase
    usage: /website

  vote:
    description: Vote Site link showcase
    usage: /vote

  map:
    description: Map (Dynmap) link showcase
    usage: /map

  wiki:
    description: Wiki / Documention link showcase
    usage: /wiki

